drop table message;

create table if not exists message
(
    id       serial
    constraint message_pk
    primary key,
    username varchar not null
    constraint message_person_username_fk
    references person (username),
    message  varchar not null
    );

alter table message
    owner to postgres;


drop table person;
create table if not exists person
(
    id            integer generated by default as identity
        primary key,
    username      varchar(100) not null,
    year_of_birth integer      not null,
    password      varchar      not null
);

